---
title: 'fingertipsR: an R package for accessing population health information in England'
author: "Sebastian Fox, Julian Flowers, Simon Thelwall, Daniel Flint, Doris Hain"
output:
  html_document: default
  html_notebook: default
  word_document: default
bibligraphy: references.bib
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(dev="png", 
               dev.args=list(type="cairo"),
               dpi=96)
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
library(fingertipsR)
library(Cairo) # for high quality graphics
library(ggplot2)
library(captioner) # for cross-referencing in article
# source(fingertips_paper_captions.R, echo = FALSE) # haven't created it yet.
```

# Abstract

This paper describes the `fingertipsR` package which provides tools for accessing the [Fingertips API](https://fingertips.phe.org.uk) to facilitate access to a wide range of public health data for England.

[Fingertips](https://fingertip.phe.org.uk) is a major public repository of population and public health indicators for England, built and maintained by Public Health England. 
The indicators are arranged in thematic or topical profiles covering a wide range of health issues including:

* broad Health Profiles
* specific topics such as liver disease and end of life
* risk factors including alcohol, smoking, physical activity
* population healthcare health services data for general practices, cancer, mental health
* health protection data on general health protection, TB, antimicrobial resistance
* lifecourse profiles for younger and older people
* mortality and morbidity.

Fingertips makes data available for more than 1500 indicators spread across more than 60 profiles and the data can be accessed from <https://fingertips.phe.org.uk> where the data are visualised in variety of ways including heatmaps, choropleth maps, line charts for trends, "spine" charts for comparing multiple indicators for a single area, scatter plots and so on.
Data can be obtained as downloads or figures which can be exported or cut and paste into reports and slides.

We recently built an [Automated Programming Interface (API)](https://fingertips.phe.org.uk/api) for the Fingertips platform to enable developers to re-use the data. 
To facilitate access we have designed an *R* package - `fingertipsR` - to facilitate rapid and easy access to the data by analysts and data scientists. 
The package is available from [CRAN](https://cran.r-project.org/).


# Introduction
 * What fingertips provides
 * What R provides (free open source)
 * Packages as a concept in R
 
[Fingertips](https://fingertip.phe.org.uk) is a major public repository of population and public health indicators for England, built and maintained by Public Health England. 
Data are organised thematically, grouping related indicators together. 
The web interface provides a interactive data visualisations allowing users to examine trends over time, geographical distribution and make comparisons between health providers. 
The web interface also provides a means to download the data behind the visualisations for re-use.
However, accessing the data in this manner limits the user to a single group of 

R is free, open source software for statistical analysis. [@r_software]
The fingertipsR package... [@fingertipsR_pkg]

# The `fingertipsR` package
 * Structure of data in fingertips – dates, area types, metadata, value notes, profiles > domains > indicators
 * Accessing the API
 * Description of functions in package

## Using the package: examples
 * Perhaps a more involved example of the deprivation/life expectancy analysis used in the vignette

## Extending the package


## Discussion/conclusions
* R packages for public health
* Writing R packages as a researcher
* Open source software- github

# references



